# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

project 'PoliceRecorder.xcodeproj'


target 'PoliceRecorder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PoliceRecorder
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'SwiftSpeech'
  pod 'SwiftyCam'

  target 'PoliceRecorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoliceRecorderUITests' do
    # Pods for testing
  end

end
